# Pre-commit hooks for MCP Manager
# See https://pre-commit.com for more information

repos:
  # ShellCheck - Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: ShellCheck
        description: Shell script analysis tool
        args: ['--severity=warning']
        files: \.sh$
        exclude: ^spec/

  # Trailing whitespace and file endings
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        exclude: \.md$
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
        files: \.(yaml|yml)$
      - id: check-json
        name: Check JSON syntax
        files: \.json$
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-executables-have-shebangs
        name: Check executables have shebangs
      - id: mixed-line-ending
        name: Check for mixed line endings
        args: ['--fix=lf']

  # Local hooks for ShellSpec tests
  - repo: local
    hooks:
      - id: shellspec-unit
        name: ShellSpec unit tests
        entry: bash -c 'if [ -x "$(command -v shellspec)" ]; then shellspec --profile --format documentation spec/unit/ || true; else echo "ShellSpec not installed, skipping tests"; fi'
        language: system
        pass_filenames: false
        files: \.(sh)$
        stages: [pre-commit]

# Configuration
default_stages: [pre-commit]
fail_fast: false
